import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).parent.resolve()
APP_VERSION = "1.2.0"
ASSETS_DIR = PROJECT_ROOT / "assets"
ICON_PATH = ASSETS_DIR / "icon.png"
CHARACTERS_DIR = ASSETS_DIR / "characters"
MODELS_DIR = PROJECT_ROOT / "models"
PERSONAS_DIR = MODELS_DIR / "personas"
PET_PERSONAS_DIR = MODELS_DIR / "pet_personas"
RUNTIME_DIR = MODELS_DIR / "runtime"
DESKTOP_AGENTS_CONFIG_PATH = MODELS_DIR / "desktop_agents.json"
APP_DB_PATH = RUNTIME_DIR / "desktop_agents.sqlite3"

LLM_PROVIDER = os.getenv("LLM_PROVIDER", "deepseek")
LLM_API_KEY = os.getenv("LLM_API_KEY", os.getenv("DEEPSEEK_API_KEY", ""))
LLM_BASE_URL = os.getenv("LLM_BASE_URL", os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1"))
LLM_MODEL = os.getenv("LLM_MODEL", os.getenv("DEEPSEEK_MODEL", "deepseek-chat"))

DEEPSEEK_API_KEY = LLM_API_KEY
DEEPSEEK_BASE_URL = LLM_BASE_URL
DEEPSEEK_MODEL = LLM_MODEL

AGENT_SIZE = 80
BREATHE_MIN_SCALE = 0.92
BREATHE_MAX_SCALE = 1.08
BREATHE_DURATION_MS = 2000

PET_SIZE = 80
PET_LABEL_HEIGHT = 24
PET_WIDGET_MARGIN = 10
PET_BREATHE_MIN_SCALE = 1.0
PET_BREATHE_MAX_SCALE = 1.04
PET_BREATHE_DURATION_MS = 2000
PET_BOUNCE_OFFSET = 8
PET_BOUNCE_DURATION_MS = 320
PET_CHAT_HISTORY_LIMIT = 8
PET_LLM_TIMEOUT_SECONDS = 20
CHAT_UI_HISTORY_LIMIT = 50
MIN_DESKTOP_AGENTS = 1
MAX_DESKTOP_AGENTS = 6
MEMORY_RECALL_STARTUP_DELAY_MS = 5000
MEMORY_RECALL_INTERVAL_MS = 30 * 60 * 1000
MEMORY_RECALL_LOOKBACK_DAYS = 7

DEFAULT_AGENT_X = 100
DEFAULT_AGENT_Y = 100
